name: Runner shell Commands
on: 
  push:
    branches:
      - 'main'
      - 'releases/**'

jobs:
 job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: Echo a String
        run: echo "Hello Securtiy Gurus!! This is our first github action"
      - name: clone repo
        uses: actions/checkout@v3
      - name: install the npm
        run: sudo apt install nodejs npm
      - name: AWS CDK installation
        run: npm install -g aws-cdk
      - name: CDK test
        run: cdk
      - name: check the working directory
        run: |
          pwd
          ls -la

 job2:
    name: job2
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Echo a String
        run: echo "Hello Securtiy Gurus!! This is our first github action"