name: Manually_triggered/workflow
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'release'
        required: false 
        type: boolean
jobs:
  dev-deploy:
    name: Deploy dev-deploy
    runs-on: ubuntu-latest
    if: ${{ inputs.tags == true}}
    steps:
    - name: step 1
      run: echo "triggered!"

  prod-deploy:
    name: Deploy prod-deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job == 'prod-deploy'}}
    steps:
    - name: ${{ github.event.inputs.job }} - step 1
      run: echo "${{ github.event.inputs.job }} triggered!"

  pre-prod:
    name: Deploy pre-prod-deploy
    runs-on: ubuntu-latest
    needs: dev-deploy
    steps:
    - name:  step 1
      run: echo  "triggered!"