name: github_action_2
on: 
  push:
    branches:
      - 'main'
      - 'releases/**'

jobs:
 job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      # - name: install the npm
      #   run: sudo apt install nodejs npm
      # - name: AWS CDK installation
      #   run: npm install -g aws-cdk
      # - name: Dependency installation
      #   run: npm install
      # - name: CDK CLODFORMATION OUTPUT
      #   run: cdk synth --output=job1

 job2:
    name: job2
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: install the npm
        run: ls #sudo apt install nodejs npm
      # - name: AWS CDK installation
      #   run: npm install -g aws-cdk
      # - name: run ci
      #   run: npm ci
      # - name: CDK CLODFORMATION OUTPUT
      #   run: cdk synth --output=job2
